const { get } = require('axios')
let MASTER_LIST = {}

/// PathCheck TEST KEY
MASTER_LIST['Rjene8QvRwA='] =
  'MIIBYDCCAQYCEQCAG8uscdLb0ppaneNN5sB7MAoGCCqGSM49BAMCMDIxIzAhBgNV\nBAMMGk5hdGlvbmFsIENTQ0Egb2YgRnJpZXNsYW5kMQswCQYDVQQGEwJGUjAeFw0y\nMTA0MjcyMDQ3MDVaFw0yNjAzMTIyMDQ3MDVaMDYxJzAlBgNVBAMMHkRTQyBudW1i\nZXIgd29ya2VyIG9mIEZyaWVzbGFuZDELMAkGA1UEBhMCRlIwWTATBgcqhkjOPQIB\nBggqhkjOPQMBBwNCAARkJeqyO85dyR+UrQ5Ey8EdgLyf9NtsCrwORAj6T68/elL1\n9aoISQDbzaNYJjdD77XdHtd+nFGTQVpB88wPTwgbMAoGCCqGSM49BAMCA0gAMEUC\nIQDvDacGFQO3tuATpoqf40CBv09nfglL3wh5wBwA1uA7lAIgZ4sOK2iaaTsFNqEN\nAF7zi+d862ePRQ9Lwymr7XfwVm0='

const ATPUBKEY =
  'MIIBIzCByqADAgECAgRi5XwLMAoGCCqGSM49BAMCMBAxDjAMBgNVBAMMBUVDLU1l\nMB4XDTIxMDQyMzEwMzc1NVoXDTIxMDUyMzEwMzc1NVowEDEOMAwGA1UEAwwFRUMt\nTWUwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAT4pyqh0AMFtrN/rLF4tKBB+Rhp\n6ttuC6JTQ4c4fIy9f6H/Hjko8v6fYWkz3WrhKV7e0ScI4RLbT6nrv/F/6sJQoxIw\nEDAOBgNVHQ8BAf8EBAMCBaAwCgYIKoZIzj0EAwIDSAAwRQIhAMQjFFnmgFx1scLH\n6+iY9Vyu3EYkHEzNXUv7Zr/H6gJDAiAw7Sry/U7h/X+Hk1MncAqln7dpK2MDKABc\n46ByFwZ+Bw=='
const SEPUBKEY =
  'MIIBYDCCAQagAwIBAgIEYGIVCzAKBggqhkjOPQQDAjA4MQswCQYDVQQGEwJTRTEN\nMAsGA1UECgwERElHRzEaMBgGA1UEAwwRSENlcnQgU2lnbmVyIFRlc3QwHhcNMjEw\nMzI5MTc1NzMxWhcNMjIwMzI5MTc1NzMxWjA4MQswCQYDVQQGEwJTRTENMAsGA1UE\nCgwERElHRzEaMBgGA1UEAwwRSENlcnQgU2lnbmVyIFRlc3QwWTATBgcqhkjOPQIB\nBggqhkjOPQMBBwNCAAQXNY8VvikJck41yqTP4ywegcKsTDsVMWlHAOPvDfzQs+n1\nT/912la9SQw4rzzyYHqoC+I+WVwwkkVcDOijb6B+MAoGCCqGSM49BAMCA0gAMEUC\nIQCgsGcnfxQGqhuX9DbmDEFS/xGW8P/Us25sRxvTkWiJIgIgFpzdl/IxggUOGe1v\n+/bI6hn43noNU4Y0f5zBEc+pBdI='

// Test servers for AT and SE
MASTER_LIST['WTOXYrYS47o='] = ATPUBKEY
MASTER_LIST['b0PE1U8EXlw='] = SEPUBKEY

get('https://de.dscg.ubirch.com/trustList/DSC').then((res) => {
  let DSC = JSON.parse(res.data.split('\n')[1])
  DSC.certificates.forEach((e) => {
    MASTER_LIST[e.kid] = e.rawData
  })
})

export async function resolveKey(kID) {
  if (!MASTER_LIST[kID]) {
    console.log('KeyID not found: ', kID)
  }
  return '-----BEGIN CERTIFICATE-----\n' + MASTER_LIST[kID] + '\n-----END CERTIFICATE-----'
}
